POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "patricio",
  "name": "mao",
  "password": "siu"
}

###
GET http://localhost:3003/api/users

###
DELETE http://localhost:3003/api/users/64dfb543721cb66ec550d372